org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.4
loader_version=0.16.14
fabric_version=0.97.3+1.20.4

mod_id=ultramarine
archives_base_name=Ultramarine
mod_version=0.5.1-snapshot
maven_group=org.voxelutopia
mod_description=A Chinese Style Minecraft Mod
mod_credits=See credits file
mod_icon=ultramarine_logo.png

# Dependencies
mixin_version=0.8.5
jei_version=17.3.1.5
jade_version_id=5111964
patchouli_version=85
worldedit_version_id=5168651

port_version=2.3.8+1.20.4