package com.voxelutopia.ultramarine.client.event;

import com.voxelutopia.ultramarine.client.render.SeatEntityRenderer;
import com.voxelutopia.ultramarine.client.screen.BrickKilnScreen;
import com.voxelutopia.ultramarine.client.screen.ChiselTableScreen;
import com.voxelutopia.ultramarine.client.screen.ContainerDecorativeBlockScreen;
import com.voxelutopia.ultramarine.client.screen.WoodworkingWorkbenchScreen;
import com.voxelutopia.ultramarine.data.registry.BlockRegistry;
import com.voxelutopia.ultramarine.data.registry.EntityTypeRegistry;
import com.voxelutopia.ultramarine.data.registry.MenuTypeRegistry;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
import net.minecraft.client.gui.screens.MenuScreens;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.WanderingTraderRenderer;

public class ModClientRenderEventHandler {

    public static void onClientSetup() {
        setRenderLayers();
        registerMenuScreens();
        registerEntityRenderers();
    }

    private static void setRenderLayers() {
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.ABACUS, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BRUSH_TOOLS, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BOTTLE_GOURD, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BLACK_IRON_FLOWERPOT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BLUE_PORCELAIN_FLOWERPOT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEMORIAL_TABLET, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.KNOCKER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PORCELAIN_TEAPOT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BRONZE_CENSER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.ROYAL_CENSER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.JADE_PENDANT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.IMPERIAL_JADE_SEAL, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.TEAHOUSE_FLAG, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PAPER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LONG_HANGING_PAINTING, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.DAMAGED_LANDSCAPE_PAINTING, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.HANGING_PAINTING_FAN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_WOODEN_GUARDIAN_LION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_STONE_GUARDIAN_LION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_JADE_GUARDIAN_LION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_YELLOW_GLAZED_GUARDIAN_LION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_GREEN_GLAZED_GUARDIAN_LION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GUNNY_SACK, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PLATED_MUNG_BEAN_CAKES, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PLATED_FISH, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WINE_POT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.OCTAGONAL_PALACE_LANTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SQUARE_PALACE_LANTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.STANDING_LAMP, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_STANDING_LAMP, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WHITE_SKY_LANTERN, RenderType.translucent());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_SKY_LANTERN, RenderType.translucent());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_SKY_LANTERN, RenderType.translucent());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.STONE_LAMP, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_WOODEN_RAILING, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_WOODEN_RAILING_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODEN_RAILING, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODEN_RAILING_VARIANT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_CARVED_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CIRCULAR_YELLOW_CARVED_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_CARVED_FANGXIN_EDGE_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_CARVED_FANGXIN_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_YELLOW_CARVED_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_YELLOW_CARVED_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_CARVED_ZHAOTOU_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LONG_YELLOW_CARVED_ZHAOTOU_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.FLAME_ARCH_WALL_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GOLDEN_DRAGON_FANGXIN_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BLUE_FANGXIN_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BLUE_FANGXIN_PATTERN_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LIGHT_BLUE_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.YELLOW_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LIGHT_YELLOW_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_WHITE_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_GREEN_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_GRAY_SU_STYLE_CAIHUA, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GREEN_FANGXIN_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GREEN_FANGXIN_PATTERN_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CARVED_ZHAOTOU_PATTERN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LONG_GILDED_DARK_OAK_QUETI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LONG_GILDED_DARK_OAK_QUETI_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODEN_QUETI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.TALL_WOODEN_QUETI_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODEN_QUETI_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SHORT_GLAZED_QUETI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_WOODEN_QUETI_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODEN_GUALUO, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_WOODEN_GUALUO, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_WOODEN_GUALUO_EDGE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.THICK_CARVED_QUETI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_BLUE_CURTAIN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_BLUE_CURTAIN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_BLUE_CURTAIN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_CURTAIN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_CURTAIN_CORNER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GLAZED_TILE_GRID_WINDOW, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CARVED_WOODEN_DOOR, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SONG_WOODEN_DOOR, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SONG_WOODEN_WINDOW, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BAMBOO_CURTAIN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_CANDLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WARPED_CABINET, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.EBONY_CABINET, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_TEA_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_LANDSCAPE_PAINTING_SCREEN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CHESS_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.HIGH_TABLE_WITH_WHITE_TOP, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CENSER_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PORCELAIN_INLAID_GRAND_CHAIR, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PORCELAIN_INLAID_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CHAIR_WITH_YELLOW_CUSHION, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PAINTED_CHAIR, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_EBONY_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.OAK_BED, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.PAINTED_SCREEN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LOTUS_BUD, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_LOTUS, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.TILTED_LOTUS_LEAF, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_LOTUS_LEAF, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_LOTUS_LEAF_CLUSTER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_LOTUS_LEAF_CLUSTER, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_LOTUS_LEAF, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_DARK_GREEN_LOTUS_LEAF, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_LOTUS_LEAF, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_RED_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_RED_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_RED_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_YELLOW_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_YELLOW_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_YELLOW_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_GREEN_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_GREEN_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_GREEN_IVY, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_LEAF_PILE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_LEAF_PILE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_LEAF_PILE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_CORAL_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.TALL_BLUE_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BAMBOO_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_PLUM_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_GREETING_PINE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.TALL_BLUE_AND_WHITE_PORCELAIN_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.GREEN_PORCELAIN_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_GREEN_PORCELAIN_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_WHITE_PORCELAIN_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_WHITE_PORCELAIN_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LARGE_GREETING_PINE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.SMALL_WHITE_PORCELAIN_VASE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.MEDIUM_GREETING_PINE_BONSAI, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.WOODWORKING_WORKBENCH, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.BRICK_KILN, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.CHISEL_TABLE, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.RED_LANTERN_STREETLIGHT, RenderType.cutout());
        BlockRenderLayerMap.INSTANCE.putBlock(BlockRegistry.LONG_TABLE, RenderType.translucent());
        BlockRenderLayerMap.INSTANCE.putBlocks(RenderType.translucent(), BlockRegistry.ICICLE, BlockRegistry.LARGE_ICICLE);
    }

    private static void registerMenuScreens() {
        MenuScreens.register(MenuTypeRegistry.CONTAINER_DECORATIVE_BLOCK_MENU_GENERIC_9X1, ContainerDecorativeBlockScreen::new);
        MenuScreens.register(MenuTypeRegistry.CONTAINER_DECORATIVE_BLOCK_MENU_GENERIC_9X3, ContainerDecorativeBlockScreen::new);
        MenuScreens.register(MenuTypeRegistry.CONTAINER_DECORATIVE_BLOCK_MENU_GENERIC_9X6, ContainerDecorativeBlockScreen::new);
        MenuScreens.register(MenuTypeRegistry.CONTAINER_DECORATIVE_BLOCK_MENU_FOOD_9X3, ContainerDecorativeBlockScreen::new);
        MenuScreens.register(MenuTypeRegistry.CONTAINER_DECORATIVE_BLOCK_MENU_FOOD_9X6, ContainerDecorativeBlockScreen::new);
        MenuScreens.register(MenuTypeRegistry.BRICK_KILN, BrickKilnScreen::new);
        MenuScreens.register(MenuTypeRegistry.CHISEL_TABLE, ChiselTableScreen::new);
        MenuScreens.register(MenuTypeRegistry.WOODWORKING_WORKBENCH, WoodworkingWorkbenchScreen::new);
    }

    private static void registerEntityRenderers() {
        EntityRendererRegistry.register(EntityTypeRegistry.SEAT, SeatEntityRenderer::new);
        EntityRendererRegistry.register(EntityTypeRegistry.TRAVELLING_MERCHANT, WanderingTraderRenderer::new);
    }
}
